### ISSUE TITLE
Communicating with the service

### ISSUE THREAD

**Issue by KenxinKun** [cassiuspaim/portimporter#3]
https://github.com/cassiuspaim/portimporter/blob/74028c55d4c641739f6de109c7fe6a848745cc36/domain/contracts.go#L6

This question goes beyond the problem statement, I'd just like to hear your thoughts. As implemented, your service will progressively load a JSON file from a mounted location and stream the different ports one at a time to your repository layer in mongo. This works quite elegantly. My extended question is: if you wanted to further develop this service, for example to be able to list existing ports or find one by ID (working with the service, and not directly with the database), how would you expand your current architecture? What protocols would you use?

I appreciate this question is beyond the requested scope, so just a few lines on your thoughts would be sufficient to show what would be the next steps in the evolution of this service.

**Comment by cassiuspaim** [comment]
Hey

I will reply back this issue still today.

**Comment by cassiuspaim** [comment]
I'm not sure I understand the question the way you want it to, so if you read and don't see what you want to know, please reply back.

The repository can be used not only to work with database, but also work with other data sources, like file or other api, like a [gateway](https://martinfowler.com/articles/gateway-pattern.html) in order to encapsulate the access to the external system or resource. Keeping with this line of thought the repository could interact with other resource using REST or gRPC or GraphQL. 
If I could I would choose gRPC to make the communication faster and would use the streaming provided by gRPC to query the Ports. The protocol used by gRPC is protocol buffers and HTTP2 besides it has integration with SSL/TSL. 
Other thing to make the queries faster would be use a cache at the application level in order avoid a new query every time the Ports need to be retrieved.

If I do not touch the points you want to know please give me more details about the problems you would like to solve or mitigate.

**Comment by KenxinKun** [comment]
No, you answered what I was looking for thanks :) I have no more questions, I'll pass my feedback to the team and they'll get in touch for next steps
